In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('/Users/advait_t/Desktop/Jio/Stock-Prediction/data/Final/error_df1DCMSHRIRAM.NS.csv')
df['Date'] = pd.to_datetime(df['Date'])
# make first 6 rows from yyyy-dd-mm to yyyy-mm-
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df = df.set_index('Date', drop = False)
df['Date'] = df.index
df.head(25)

# df['Date'][0:6] = pd.to_datetime(df['Date'][0:6], format='%Y-%m-%d')
# df['Date'][0:6] = df['Date'][0:6].dt.strftime('%Y-%m-%d')

,Date,Actual_Close,Predicted_Close,Predicted_Close_Minimum,Predicted_Close_Maximum,Percent_Change_from_Close,Actual_Up_Down,Predicted_Up_Down,Company,Unnamed: 9,Date.1
Date,,,,,,,,,,,
2022-07-04,2022-07-04,942.200012,NaN,NaN,NaN,NaN,Down,NaN,DCMSHRIRAM.NS,NaN,NaN
2022-07-05,2022-07-05,953.849976,987.504999,951.498317,1019.488060,-3.528335,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-06,2022-07-06,976.200012,987.928820,950.222114,1021.016735,-1.201476,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-07,2022-07-07,960.400024,963.031872,929.957519,997.871111,-0.274037,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-08,2022-07-08,953.599976,956.072702,921.163235,990.044328,-0.259304,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-11,2022-07-11,975.450012,968.799688,933.396610,1005.632764,0.681770,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-12,2022-07-12,964.750000,974.182903,937.729741,1008.098450,-0.977756,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-13,2022-07-13,961.700012,971.606688,936.746421,1007.237448,-1.030121,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-14,2022-07-14,961.599976,972.610939,938.056174,1008.066004,-1.145067,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-15,2022-07-15,1018.450012,969.559901,933.041629,1004.612374,4.800443,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-18,2022-07-18,997.799988,975.286144,939.533171,1009.767193,2.256348,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-19,2022-07-19,984.549988,991.781881,956.975545,1028.841819,-0.734538,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-20,2022-07-20,984.500000,1001.706157,965.708186,1036.279926,-1.747705,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-21,2022-07-21,972.150024,988.992886,951.261792,1024.240786,-1.732537,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-22,2022-07-22,971.500000,982.758290,946.962245,1021.007569,-1.158856,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-25,2022-07-25,967.250000,942.832051,907.892756,980.496892,2.524471,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-26,2022-07-26,954.400024,925.039423,891.428619,962.406083,3.076341,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-27,2022-07-27,956.700012,914.071873,879.305388,945.397096,4.455748,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-28,2022-07-28,962.349976,922.876655,890.241747,960.403726,4.101764,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-29,2022-07-29,1000.049988,921.626595,888.999438,957.196890,7.841947,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-08-01,2022-08-01,1015.150024,880.648292,847.223088,918.475156,13.249444,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-08-02,2022-08-02,995.400024,875.086283,837.806846,909.065246,12.086974,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-08-03,2022-08-03,1007.700012,890.001945,855.041974,926.320010,11.679872,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-08-04,2022-08-04,1048.849976,899.883356,863.129595,936.360227,14.202853,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-08-05,2022-08-05,1039.050049,905.161363,871.697566,942.013534,12.885682,Down,Up,DCMSHRIRAM.NS,NaN,NaN

In [16]:
df.head(20)

,Date,Actual_Close,Predicted_Close,Predicted_Close_Minimum,Predicted_Close_Maximum,Percent_Change_from_Close,Actual_Up_Down,Predicted_Up_Down,Company,Unnamed: 9,Date.1
Date,,,,,,,,,,,
2022-07-04,2022-07-04,942.200012,NaN,NaN,NaN,NaN,Down,NaN,DCMSHRIRAM.NS,NaN,NaN
2022-07-05,2022-07-05,953.849976,987.504999,951.498317,1019.488060,-3.528335,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-06,2022-07-06,976.200012,987.928820,950.222114,1021.016735,-1.201476,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-07,2022-07-07,960.400024,963.031872,929.957519,997.871111,-0.274037,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-08,2022-07-08,953.599976,956.072702,921.163235,990.044328,-0.259304,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-11,2022-07-11,975.450012,968.799688,933.396610,1005.632764,0.681770,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-12,2022-07-12,964.750000,974.182903,937.729741,1008.098450,-0.977756,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-13,2022-07-13,961.700012,971.606688,936.746421,1007.237448,-1.030121,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-14,2022-07-14,961.599976,972.610939,938.056174,1008.066004,-1.145067,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-15,2022-07-15,1018.450012,969.559901,933.041629,1004.612374,4.800443,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-18,2022-07-18,997.799988,975.286144,939.533171,1009.767193,2.256348,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-19,2022-07-19,984.549988,991.781881,956.975545,1028.841819,-0.734538,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-20,2022-07-20,984.500000,1001.706157,965.708186,1036.279926,-1.747705,Down,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-21,2022-07-21,972.150024,988.992886,951.261792,1024.240786,-1.732537,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-22,2022-07-22,971.500000,982.758290,946.962245,1021.007569,-1.158856,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-25,2022-07-25,967.250000,942.832051,907.892756,980.496892,2.524471,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-26,2022-07-26,954.400024,925.039423,891.428619,962.406083,3.076341,Down,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-27,2022-07-27,956.700012,914.071873,879.305388,945.397096,4.455748,Up,Down,DCMSHRIRAM.NS,NaN,NaN
2022-07-28,2022-07-28,962.349976,922.876655,890.241747,960.403726,4.101764,Up,Up,DCMSHRIRAM.NS,NaN,NaN
2022-07-29,2022-07-29,1000.049988,921.626595,888.999438,957.196890,7.841947,Up,Down,DCMSHRIRAM.NS,NaN,NaN

In [20]:
# fetch data from yahoo finance for the company DCMSHRIRAM.NS from 4th July 2022 to today
import yfinance as yf
df = yf.download('HDFCBANK.NS', start='2022-07-04', end='2022-10-18')
df = df.reset_index()
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df = df.set_index('Date', drop = False)
df['Date'] = df.index
df.head(20)

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2022-07-04,2022-07-04,1353.699951,1360.199951,1342.250000,1355.650024,1355.650024,4243740
2022-07-05,2022-07-05,1364.000000,1379.349976,1348.300049,1352.599976,1352.599976,7162859
2022-07-06,2022-07-06,1348.000000,1373.400024,1347.099976,1371.250000,1371.250000,7524539
2022-07-07,2022-07-07,1380.000000,1398.000000,1374.449951,1395.800049,1395.800049,8871571
2022-07-08,2022-07-08,1410.000000,1410.000000,1394.750000,1397.099976,1397.099976,6237015
2022-07-11,2022-07-11,1394.000000,1409.900024,1393.250000,1406.150024,1406.150024,3731416
2022-07-12,2022-07-12,1405.250000,1405.250000,1389.400024,1391.800049,1391.800049,4938487
2022-07-13,2022-07-13,1390.000000,1394.199951,1354.250000,1357.849976,1357.849976,7972805
2022-07-14,2022-07-14,1362.000000,1372.650024,1349.250000,1351.050049,1351.050049,5186205
2022-07-15,2022-07-15,1353.000000,1364.900024,1346.800049,1362.050049,1362.050049,6797823
2022-07-18,2022-07-18,1348.000000,1366.099976,1342.050049,1347.550049,1347.550049,10166110
2022-07-19,2022-07-19,1337.000000,1358.550049,1337.000000,1348.050049,1348.050049,7896269
2022-07-20,2022-07-20,1359.900024,1371.099976,1355.250000,1365.050049,1365.050049,10173931
2022-07-21,2022-07-21,1360.550049,1369.500000,1358.099976,1360.750000,1360.750000,6320139
2022-07-22,2022-07-22,1366.000000,1397.000000,1362.400024,1392.500000,1392.500000,6364796
2022-07-25,2022-07-25,1395.000000,1404.599976,1383.300049,1396.599976,1396.599976,5071563
2022-07-26,2022-07-26,1396.000000,1402.000000,1386.300049,1393.750000,1393.750000,4263982
2022-07-27,2022-07-27,1388.900024,1406.000000,1384.250000,1404.400024,1404.400024,4606389
2022-07-28,2022-07-28,1415.050049,1424.000000,1411.000000,1416.849976,1416.849976,8710203
2022-07-29,2022-07-29,1438.000000,1438.599976,1415.300049,1434.199951,1434.199951,10009868